title: Edouard Pineau
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD student at [Institut Polytechnique de Paris](https://www.ip-paris.fr/en/home-en/)
  <br><br>
  <a href="https://www.linkedin.com/in/edouard-pineau-b8820391/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
